export const permissions = [
  { name: "addAppointment" },
  { name: "getPatientAppointment" },
  { name: "getAppointment" },
  { name: "showAppointmnetDetail" },
  { name: "updateStatus" },
  { name: "updateAppointment" },
  { name: "addDoctor" },
  { name: "updateDoctor" },
  { name: "listDoctors" },
  { name: "showDoctorDetails" },
  { name: "DeactiveDoctor" },
  { name: "createInvoice" },
  { name: "listInvoice" },
  { name: "updateInvoiceDetail" },
  { name: "Show_Invoice_Details" },
  { name: "List_Invoice_Details" },
  { name: "Append_Invoice_Details" },
  { name: "Remove_Invoice_Details" },
  { name: "addPatient" },
  { name: "updatePatient" },
  { name: "listPatient" },
  { name: "getPatient" },
  { name: "createRole" },
  { name: "allRoles" },
  { name: "assignRoleToUser" },
  { name: "getAllRoleUsers" },
  { name: "updateRole" },
  { name: "deleteRole" },
  { name: "addSchedule" },
  { name: "listSchedules" },
  { name: "showScheduleDetails" },
  { name: "updateSchedule" },
  { name: "deleteSchedule" },
  { name: "addService" },
  { name: "allServices" },
  { name: "updateService" },
  { name: "getService" },
  { name: "deactiveService" },
  { name: "createSpecialty" },
  { name: "updateSpecialty" },
  { name: "allSpecialtys" },
  { name: "getOneSpecialty" },
  { name: "addUser" },
  { name: "allUsers" },
  { name: "getOneUser" },
  { name: "updateUser" },
  { name: "deactiveUser" },
  { name: "DeleteUser" },
  { name: "createVisit" },
  { name: "showVisitDetails" },
  { name: "getAllVisits" },
  { name: "appendVisitDetails" },
  { name: "removeVisitDetails" },
  { name: "deleteVisit" },
  { name: "summarized_report" },
  { name: "downloadPdf" },
  { name: "listDates" },
  { name: "search" },
  { name: "seedPermissions" },
  { name: "assignPermissionsToUser" },
  { name: "assignPermissionsToRole" },
  { name: "ListPermissions" },
  { name: "ListUserPermissions" },
  { name: "ListRolePermissions" },
  { name: "deleteInvoice" },
  { name: "profile" },
];

[
  "addAppointment",
  "getPatientAppointment",
  "getAppointment",
  "showAppointmnetDetail",
  "updateStatus",
  "updateAppointment",
  "addDoctor",
  "updateDoctor",
  "listDoctors",
  "showDoctorDetails",
  "DeactiveDoctor",
  "createInvoice",
  "listInvoice",
  "updateInvoiceDetail",
  "Show_Invoice_Details",
  "List_Invoice_Details",
  "Append_Invoice_Details",
  "Remove_Invoice_Details",
  "addPatient",
  "updatePatient",
  "listPatient",
  "getPatient",
  "createRole",
  "allRoles",
  "assignRoleToUser",
  "getAllRoleUsers",
  "updateRole",
  "deleteRole",
  "addSchedule",
  "listSchedules",
  "showScheduleDetails",
  "updateSchedule",
  "deleteSchedule",
  "addService",
  "allServices",
  "updateService",
  "getService",
  "deactiveService",
  "createSpecialty",
  "updateSpecialty",
  "allSpecialtys",
  "getOneSpecialty",
  "addUser",
  "allUsers",
  "getOneUser",
  "updateUser",
  "deactiveUser",
  "DeleteUser",
  "createVisit",
  "showVisitDetails",
  "getAllVisits",
  "appendVisitDetails",
  "removeVisitDetails",
  "deleteVisit",
  "summarized_report",
  "downloadPdf",
  "listDates",
  "search",
  "seedPermissions",
  "assignPermissionsToUser",
  "assignPermissionsToRole",
  "ListPermissions",
  "ListUserPermissions",
  "ListRolePermissions",
  "deleteInvoice",
  "profile",
];
